require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - dev/**/*

# The `ConfigValidator` class is a DSL, let it be
Metrics/AbcSize:              { Exclude: [lib/bashly/config_validator.rb] }
Metrics/CyclomaticComplexity: { Exclude: [lib/bashly/config_validator.rb] }
Metrics/PerceivedComplexity:  { Exclude: [lib/bashly/config_validator.rb] }
Metrics/MethodLength:         { Exclude: [lib/bashly/config_validator.rb] }
Style/GuardClause:            { Exclude: [lib/bashly/config_validator.rb] }

# Allow irregular filenames in some cases
RSpec/FilePath:
  Exclude:
    - 'spec/bashly/concerns/completions_command_spec.rb'
    - 'spec/bashly/concerns/completions_flag_spec.rb'

