describe Libraries::CompletionsScript do
  subject { described_class.new(*args) }

  let(:args) { nil }

  before { reset_tmp_dir example: 'minimal' }

  describe '#files' do
    it 'returns one file at the default path' do
      files = subject.files

      expect(files.size).to eq 1
      expect(files.first[:path]).to eq "#{Settings.target_dir}/completions.bash"
    end

    it 'returns the completions script content' do
      content = subject.files.first[:content]

      expect(content).to include '# download completion'
      expect(content).to include 'generated by'
      expect(content).to include 'completely'
      expect(content).to include 'complete -F _download_completions download'
    end

    context 'with an argument' do
      let(:args) { ['filename.bash'] }

      it 'uses the first argument as a filename' do
        expect(subject.files.first[:path]).to eq args.first
      end
    end
  end

  describe '#post_install_message' do
    it 'returns a message' do
      expect(subject.post_install_message).to match_approval('libraries/completions_script/message')
    end
  end
end
