describe Libraries::CompletionsFunction do
  subject { described_class.new(*args) }

  let(:args) { nil }

  before { reset_tmp_dir example: 'minimal' }

  describe '#files' do
    it 'returns one file at the default path' do
      files = subject.files

      expect(files.size).to eq 1
      expect(files.first[:path]).to eq "#{Settings.source_dir}/lib/send_completions.sh"
    end

    it 'returns the completions function content' do
      content = subject.files.first[:content]

      expect(content).to include '## [@bashly-upgrade completions send_completions]'
      expect(content).to include 'send_completions() {'
      expect(content).to include 'generated by'
      expect(content).to include 'completely'
    end

    context 'with an argument' do
      let(:args) { ['my_function'] }

      it 'uses the first argument in the filename of [:path]' do
        expect(subject.files.first[:path]).to eq "#{Settings.source_dir}/lib/#{args.first}.sh"
      end

      it 'uses the first argument as the function of [:content]' do
        expect(subject.files.first[:content]).to include 'my_function()'
        expect(subject.files.first[:content]).to include '[@bashly-upgrade completions my_function]'
      end
    end
  end

  describe '#post_install_message' do
    it 'returns a message' do
      expect(subject.post_install_message).to match_approval('libraries/completions_function/message')
    end
  end
end
